### ISSUE TITLE
Error evolution_generations.py

### ISSUE THREAD

**Issue by Eroso** [Gab0/gekkoJaponicus#14]
Hi,

Thanks for for your work.
I have a problem when I run the program.

> py -2 japonicus.py -g --repeat 100 --strat RSI

>Traceback (most recent call last):
>  File "japonicus.py", line 9, in <module>
    from evolution_generations import gekko_generations
  File "C:\Users\User\Downloads\gekkoJaponicus\evolution_generations.py", line 36
    print("\r\tevaluating %i:\t%.2f%%" % (l, ((w+1)/l*100)), end='')
                                                                ^
SyntaxError: invalid syntax

There appears to be a problem in line 36 of the file evolution_generations.py but I do not know how to solve it.

Thanks

**Comment by Gab0** [comment]
What stands for `py -2`?
If it's about python 2.7, try to run this on python 3.6 ^^
