### ISSUE TITLE
 help in installing genetic algorithm

### ISSUE THREAD

**Issue by JHON198477** [Gab0/gekkoJaponicus#18]
it would be satisfactory for me to achieve the correct installation of the genetic algorithm, where I get to know a step by step how to do it, since I am new to this subject. Thank you

**Comment by JHON198477** [comment]
I have followed these steps for the installation of the genetic algorithm:

1.git clone https://github.com/Gab0/gekkoJaponicus.git
2.pip install deap requests numpy
3.Than run gekko with the ui
4. Finally cd into the cloned folder and python evolution.py

but I get this error,

gekko@jhon:~/gekko$ cd gekkoJaponicus
gekko@jhon:~/gekko/gekkoJaponicus$ python evolution.py
  File "evolution.py", line 23
    print("\r\tevaluating %i:\t%.2f%%" % (l, ((w+1)/l*100)), end='')
                                                                ^
SyntaxError: invalid syntax

what can i do to solve this...

**Comment by gucio1200** [comment]
Python version , use 3.6

**Comment by gucio1200** [comment]
Btw. u have same topic and same problem in 1 subject below...

**Comment by JHON198477** [comment]
install python 3.6, still has the same error, what will be the problem?

**Comment by gucio1200** [comment]
And u r running by "python3.6 evolution.py" ?

**Comment by JHON198477** [comment]
run the previous command "python3.6 evolution.py" but now change the error.

gekko@jhon:~/gekko/gekkoJaponicus$ python3.6 evolution.py
Traceback (most recent call last):
  File "evolution.py", line 8, in <module>
    from deap import base
ModuleNotFoundError: No module named 'deap'



gekko@jhon:~/gekko/gekkoJaponicus$ python3.6 evolution.py
Traceback (most recent call last):
  File "evolution.py", line 8, in <module>
    from deap import base
ModuleNotFoundError: No module named 'deap'

**Comment by Gab0** [comment]
@JHON198477 at this folder you are at, run 
`sudo pip3.6 -i requirements.txt`

**Comment by JHON198477** [comment]
run the above command but it has this error:
gekko @ jhon: ~ / gekko / gekkoJaponicus $ `sudo pip3.6 -i requirements.txt`

Usage:
  pip <command> [options]

no such option: -i

run the following `sudo pip install -r requirements.txt` command to install the requtirments.txt into the gekkoJaponucus folder, but the same error still occurs.

 gekko @ jhon: ~ / gekko / gekkoJaponicus $ `python3.6 evolution.py`
Traceback (most recent call last):
  File "evolution.py", line 8, in <module>
    from deap import base
ModuleNotFoundError: No module named 'deap'

**Comment by Gab0** [comment]
@JHON198477 hah sorry man, it's `-r` indeed.. edited my answer so I don't look dumb.
you ran pip for the correct version? (`pip3 or pip3.6    this is important`). PIP ran fine? Did it find all the packages? This is a strange error.

**Comment by JHON198477** [comment]
I could help with the commands to download and install `pip3.6.` I searched the web and did not find them.

**Comment by Gab0** [comment]
@JHON198477 Maybe your bare pip is already for python 3.6 (check with `pip --version`)
