### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by joernroeder** [Gab0/gekkoJaponicus#27]
i would love to run this insinde a docker container :)

**Comment by greenbigfrog** [comment]
@Gab0 in the future referencing issue's and PRs in commits etc. will help follow, if a certain issue was actually fixed or not. In this particular case it's impossible to tell, if a Dockerfile was added or not, without checking if the file exists.

**Comment by Gab0** [comment]
Haa that's real.. repo is very disorganized atm, trying to get things sane here... Dockerfile was added ^^
#29

**Comment by Gab0** [comment]
#29
