### ISSUE TITLE
graph breaks after x epochs

### ISSUE THREAD

**Issue by joernroeder** [Gab0/gekkoJaponicus#28]
The following graph looked good at the beginning but reshaped after some time.
![screen shot 2017-11-01 at 01 21 34](https://user-images.githubusercontent.com/270540/32254759-531c2bce-bea3-11e7-8ecc-d113ce926cff.PNG)

**Comment by Gab0** [comment]
haha modern art
graph is broken since parallel locales were implemented.. I will fix it

**Comment by Gab0** [comment]
fixed;
