### ISSUE TITLE
Error: config failure

### ISSUE THREAD

**Issue by xwolfyxNL** [Gab0/gekkoJaponicus#30]
I am getting the following error: https://pastebin.com/akErvRyT
I also see in the settings that its looking for a "example-config.js" but I can't find this anywhere and I also wouldn't know what it should contain could you maybe give an example?

Running the command: sudo python3.6 japonicus.py -g -c -w -r

**Comment by Gab0** [comment]
can you confirm those dates are inside your dataset ranges? 
`'backtest': {'daterange': {'from': '2017-09-29 01:40:15', 'to': '2017-10-20 01:40:15'}}`

does gekko error report something useful? also, please try `-gcw --strat PPO`

**Comment by xwolfyxNL** [comment]
I didn't enter that date and I can't find it in the settings.py, where do I need to set that date?
And where can I find the " 'configFilename': 'example-config.js' "?
As I don't see it anywhere and I wouldn't know what data I need to put in that file. Could you give an example?

**Comment by Gab0** [comment]
man can you backtest on Gekko alone? you just need to have loadable candlestick history data on your gekko. No Settings.py involved.
example-config.js is the gekko config file, it's on gekko folder.. put in a path to it it's only for bayesian evolution.

**Comment by Nophi** [comment]
Hi Gab0,
I have the same problem
When I launch Japonicus :  python3 japonicus.py -gc --strat RSI
Here is the return : [https://pastebin.com/th1Ke4Wn](https://pastebin.com/th1Ke4Wn)
And in gekko, I have these errors : [https://pastebin.com/sAH8JPNZ](https://pastebin.com/sAH8JPNZ)
I have talib 1.0.2.

Thanks

**Comment by Gab0** [comment]
At Settings.py there is this 'dataset_source' key:
```
            'dataset_source': {
                "exchange": "poloniex",
                "currency": 'USDT',
                "asset": 'BTC'
            },
```
Fill it with your candlestick database specifications or just set `'dataset_source: None,` so japonicus auto-selects..
Sorry guys, it might be this .. readmes arent always perfect :3

**Comment by xwolfyxNL** [comment]
I have set this info but it still searches for poloniex, USDT, BTC.
I set mine to this:
`            'dataset_source': { # dataset_source can be set to None so it searches from any source;
                "exchange": "gdax",
                "currency": 'EUR',
                "asset": 'LTC'
            },

**Comment by Nophi** [comment]
Hi,
i have test with this config

> 
          'dataset_source': { 
                "exchange": "bitfinex",
                "currency": 'USD',
                "asset": 'BTC'
            },

And with `'dataset_source': None,`

The result is the same, the problem persists.
The date sets are correct.

Thanks

**Comment by xwolfyxNL** [comment]
@Nophi Where did you set the date sets? as they don't seem to work for me. Example would be appreciated :)

**Comment by Gab0** [comment]
Hmm I know this error on `root/gekko/node_modules/koa/lib/context.js`.... can you list your candlestick databases? I will download those candles of @Nophi; I only use poloniex so something may be wrong.

**Comment by Nophi** [comment]
My date sets is : 
![2017-11-27 15_14_29-gekko](https://user-images.githubusercontent.com/20139334/33270913-ed1d117e-d385-11e7-80ae-24f24fae7103.png)

And in Japonicus log :
![2017-11-27 15_17_27-remote desktop manager srv gekko - ssh](https://user-images.githubusercontent.com/20139334/33270967-1d694956-d386-11e7-9885-a10127e3391c.png)

I just config my Settings.py with this parameter :

> 'dataset_source': { 
            "exchange": "bitfinex",
            "currency": 'USD',
            "asset": 'BTC'
        },

And automatically, it takes good data sets.

**Comment by xwolfyxNL** [comment]
Jep that works for me 2.
Seems it isn't sending the correct settings to the EPOCH's

**Comment by Gab0** [comment]
@xwolfyxNL & @Nophi Thanks, u guys... there is an error indeed on candlestick data loading on japonicus... to fix that I need to have a database that is not poloniex USD/BTC myself, please wait :}

**Comment by Gab0** [comment]
nevermind... importer is @ 5% but it seems I got it fixed;
Just pull and try... or wait for the confirmation
in time: on Gekko there is a open pull request about `sharpe` fix, it's recommended to apply that patch, its important for japonicus results.
thanks!

**Comment by xwolfyxNL** [comment]
It seems to be running now thanks for the help and fix @Gab0

**Comment by xwolfyxNL** [comment]
@Gab0 It works now only the webinterface doesn't work and gives the following errors: https://pastebin.com/5gECeheu

**Comment by Gab0** [comment]
@xwolfyxNL thats really a bug on the web interface ^^
aside that, the web graphics are somewhat useless right now... they worked fine until gekko changed to parallel GA; fixes are coming but I need to learn about dash/flask :/

**Comment by Nophi** [comment]
It works fine with bitfinex, thanks !
I have a same problem with the web interface :)
Thanks for your support !

**Comment by Gab0** [comment]
So all fixed
Even the web interface ;D
