### ISSUE TITLE
Describing the commits

### ISSUE THREAD

**Issue by phatwila** [Gab0/gekkoJaponicus#32]
Hey, I love the work you've done with this so far, but could you start adding commit messages with what you've changed instead of a period for your pushes to master? It would make it a lot easier for everyone who's interested in knowing whats changed at a glance.

Thank you!

**Comment by Gab0** [comment]
All the commits I have done last week are bugfixes, and should be pulled asap really. 
Soon we'll be able to actually improve the algo, then I will surely start to add commit messages..
Thanks for the tip

**Comment by rdetwiler** [comment]
Thank you so much!
