### ISSUE TITLE
Refactor broke build

### ISSUE THREAD

**Issue by stephenthoma** [Gab0/gekkoJaponicus#36]
574f6c17de2bf0737cd17996dd132dc6e0155655 changes to oldschool.py are breaking build on Master. Specifically removal of Creator.

**Comment by phatwila** [comment]
I found a temporary workaround is to use -gc instead of just -g till its fixed.

**Comment by stephenthoma** [comment]
@phatwila pushed up my branch with fix if you want it

**Comment by Gab0** [comment]
A bug indeed ^^ im pushing the fixes..
