### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by madaerodog** [Gab0/gekkoJaponicus#38]
Hey guys,

I keep getting this, any idea why?

I ran python3 japonicus.py -g --strat RSI -w with the latest gekko in paralel.

Traceback (most recent call last):
  File "japonicus.py", line 93, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode, web=APP)
  File "/home/constantin/Development/gekkoJaponicus/evolution_generations.py", line 77, in gekko_generations
    exchange_source=genconf.dataset_source)
  File "/home/constantin/Development/gekkoJaponicus/promoterz/evaluation/gekko.py", line 69, in getAvailableDataset
    raise "scanset not available: {}".format(watch)
NameError: name 'watch' is not defined

**Comment by madaerodog** [comment]
Hmm I believe it might be connected to the fact that I have not imported any local data in Gekko. But when I will how do you select on what data set to work unless it's only one ...

**Comment by Gab0** [comment]
NameError raised while raising an exception lol what a buggy software : '(
But yeah, that's because you don't have local data. Import some data and try it...

**Comment by madaerodog** [comment]
All good, running now.
