### ISSUE TITLE
ImportError: cannot import name supplement

### ISSUE THREAD

**Issue by peter-umb** [Gab0/gekkoJaponicus#39]
Gekko is setup and working. Japonicus seems to be having an issue with the supplement file.

Ubuntu 17.04 - Node 6.12.1 - Gekko v0.5.10

python japonicus.py -g
Traceback (most recent call last):
  File "japonicus.py", line 8, in <module>
    from evolution_generations import gekko_generations
  File "/home/pete/Projects/gekko/gekkoJaponicus/evolution_generations.py", line 4, in <module>
    import promoterz
  File "/home/pete/Projects/gekko/gekkoJaponicus/promoterz/__init__.py", line 5, in <module>
    from . import supplement, validation, utils
ImportError: cannot import name supplement

**Comment by Gab0** [comment]
You shoud specity a strat, like in `python japonicus.py -g --strat PPO`. See if it works ^^

**Comment by Gab0** [comment]
That ImportError is still strange, though... make sure used python is version >= 3.5

**Comment by peter-umb** [comment]
I updated to Python 3.5.2+ and now I have a new error.

python3 japonicus.py -g --strat
Traceback (most recent call last):
  File "japonicus.py", line 7, in <module>
    from Settings import getSettings
  File "/home/pete/Projects/gekko/gekkoJaponicus/Settings.py", line 3, in <module>
    import js2py
ImportError: No module named 'js2py'

**Comment by Gab0** [comment]
Missing module...
Since you updated python, u should install requirements again with pip

**Comment by peter-umb** [comment]
You are correct. It was dependencies. I am now able to get to the help command but I am having trouble starting. Can you point me in the direction of a working japonicus --strat command? Even if all it does is sell high and buy low.

**Comment by Gab0** [comment]
Nice question, so the readme got updated with da answer, under `Gekko Strategies` section, hope it helps ;d
