### ISSUE TITLE
Non-ASCII Character encountered, no encoding declared

### ISSUE THREAD

**Issue by anakaine** [Gab0/gekkoJaponicus#41]
This errors on Ubuntu: Python 2.7

i5ubuntu@ubuntu:~/Downloads/gekkoJaponicus$ python japonicus.py -g -i -w
  File "japonicus.py", line 24
SyntaxError: Non-ASCII character '\xe2' in file japonicus.py on line 25, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by ravin353** [comment]
Add this line on top of japonicus.py file

# -*- coding: utf-8 -*-

**Comment by Gab0** [comment]
Hey @anakaine, on python 2.7 a lot more problems will happen. japonicus works on python3.6
