### ISSUE TITLE
Unable to use current master

### ISSUE THREAD

**Issue by pharindoko** [Gab0/gekkoJaponicus#43]
Hi,

it does not work when I try to execute 
```
python japonicus.py
```

# What I did ?

Executed script on both Windows 7 and Ubuntu

Used Python 2.7 and 3

**ErrorMessage:** 
```
D:\gekko\gekkoJaponicus>python japonicus.py
  File "japonicus.py", line 24
SyntaxError: Non-ASCII character '\xe2' in file japonicus.py on line 25, b
encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
==> this is due to utf-8 

But even when I fix this one I receive additional import errors for supplement and other errors (e.g. from urllib import Request, Parse)

# What worked:
Installation:
```
$ git clone https://git.com/Gab0/gekkoJaponicus.git
$ cd gekko_japonicus
$ sudo pip install -r requirements.txt
```
Gekko itself works:
```
node gekko.js --ui
```

# What help I try to get ?

@Gab0  
Can you verify that this works on Windows or Ubuntu when you install and execute it completely new ?
Which version of python I should use ?

**Comment by xteejx** [comment]
I can also confirm the import of supplement does not work.
Also the utf8 encoding for the title banner is likely the cause of the issue and the fallback does not work.

**Comment by xteejx** [comment]
Using python 3.6 works for me. This should be added to the readme as a requirement

**Comment by Gab0** [comment]
Yeah, those errors are due to wrong python version.
