### ISSUE TITLE
getDateRange function is not defined

### ISSUE THREAD

**Issue by obie73** [Gab0/gekkoJaponicus#8]
In the step bayesian optimization throw this exception
File "/home/julio/gekkoJaponicus/evolution_bayes.py", line 213, in gekko_bayesian
    DateRange = getDateRange(chosenRange, deltaDays=settings['testDays'])
NameError: name 'getDateRange' is not defined

I check the file and not found this function.

Thanks for your work!
Cheers!

**Comment by Gab0** [comment]
Thanks for the report.
This error is gone.. But I tried to integrate both methods in a nice frontend script in such a way that evolution_bayes is now broken (I didn't write bayes).  We got only GA atm : 3
@mainyaa Could you take a look and fix those global variables? Sorry man xD 

The first evolution_bayes on repo history works, of course.
