### ISSUE TITLE
MACD and DEMA Strategy

### ISSUE THREAD

**Issue by obie73** [Gab0/gekkoJaponicus#9]
Hello, the program generates the following settings for testing

```
config.MACD = {
  "long": 20.843421695138005,
  "thresholds": {
    "persistence": 1.6903547506318077,
    "up": -0.012428340696021,
    "fibonacci": 0.1383140595900251,
    "high": 58.04953295840107,
    "low": 22.09129066200335,
    "down": 0.0005979862069472319
  },
  "short": 21.680672087431585,
  "interval": 3.774585878395658,
  "signal": 8.56230083381508
}
```
but my MACD strategy file and my DEMA startegy file lacks the following variables fibonacci, high and low.
Could you pass me a strategy files that you use to do these tests?
Sorry for the request but I'm a real noob in this. And I have some problem to understand English.

Thanks a lot!!

**Comment by Gab0** [comment]
haa those parameters are for custom indicators found here -> https:git.com/thegamecat/gekko-trading-stuff;
You know.. paste them to strategies/indicators folder and edit plugins/tradingAdvisor/baseTradingMethod.js,
adding them to array Indicators (input: 'candle' for both TWIG and FIBO).
I got no strategies that use them, you have to search or make one :/

**Comment by obie73** [comment]
Is it possible to remove these indicators from the GA test? 
Could I try another strategy?

Thanks!

**Comment by Gab0** [comment]
All those settings are defined on reconstructTradeSettings@coreFunctions.py... they can be modified at no cost, also no benefit.
Yeah, chosen strategy is defined at Settings.py, under 'generations'.
